# Build the Next.js application
FROM node:18-alpine AS base

# Set the working directory in the container
WORKDIR /frontend

# COPY the current directory contents into the container at /frontend
COPY . /frontend

# INSTALL any packages
RUN npm install

# Make port 3000 available 
EXPOSE 3000

RUN npm run build

# Start the Next.js application
CMD ["npm", "start"]
