# Build the Next.js application
FROM node:18-alpine AS base

# Set Working directory
WORKDIR /app

# Copy package.json and package-lock.json into container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of application
COPY . .

# Build the Next.js application
RUN npm run build 

# Install 'serve' to serve the production build
RUN npm install -g serve 

# Expose the port the app runs on
EXPOSE 3000

# Start the Next.js application
CMD ["serve", "-s", "out", "-l", "3000"]
