# docker-compose.yml
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports: 
      - "27017:27017"
    networks:
      - app_network
  
  backend:
    build: ./backend
    container_name: llm_app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - app_network
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

networks:
  app_network:
    driver: bridge