# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports: 
      - "27017:27017"
    networks:
      - app_network
  
  app:
    build: .
    container_name: llm_app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    environment:
      - OPENAI_API_KEY=""
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - app_network

networks:
  app_network:
    driver: bridge