# Dockerfile
FROM python:3.12

# Set the working directory
WORKDIR /backend

# Copy the requirements txt
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy the application code
COPY app/ .

# Make port available to the world outside this container
EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]